### ISSUE TITLE
Norwegian text in English README

### ISSUE THREAD

**Issue by eirikvaa** [sigmundholm/MA8502-dealii#1]
The start of the README is written in Norwegian, should translate this part to English for consistency :-)

> ### Kompilere med cutFEM
> Endte med å måtte sette path til DealiiCutElements når jeg kjører cmake:

**Comment by sigmundholm** [comment]
I'm not sure if I understand what you mean, a PR would be much appreciated. Always looking for contributors!

**Comment by eirikvaa** [comment]
Check out #2
